<?php

return [
    'tableColumns'     => [
        'de' => [
            'Fabrik',
            'Stufe',
            'Produkt',
            'Abhängigkeiten',
            'Auslastung',
            'Umsatz',
            'Umsatz pro Ausbau',
            'Ausbaukosten',
            'Amortisierung',
        ],
        'en' => [
            'Factory',
            'Factory Level',
            'Product',
            'Dependencies',
            'Workload',
            'Turnover',
            'Turnover Increase per Uprade',
            'Upgrade Cost',
            'ROI',
        ],
    ],
    'inputPlaceholder' => [
        'de' => 'Stufe',
        'en' => 'Level',
    ],
    'factoryNames'     => [
        'de' => [
            6   => 'Betonfabrik',
            23  => 'Düngemittelfabrik',
            25  => 'Ziegelei',
            29  => 'Insektizidefabrik',
            31  => 'Eisenhütte',
            33  => 'Aluminiumfabrik',
            34  => 'Silberraffinerie',
            37  => 'Kupferfabrik',
            39  => 'Ölraffinerie',
            52  => 'Titanraffinerie',
            61  => 'Glaserei',
            63  => 'Kunststofffabrik',
            68  => 'Siliziumraffinerie',
            69  => 'Elektronikfabrik',
            76  => 'Medizintechnik Inc.',
            80  => 'Goldraffinerie',
            85  => 'Goldschmied',
            91  => 'Lithiumraffinerie',
            95  => 'Batteriefabrik',
            101 => 'Waffenfabrik',
            118 => 'Scandrohnenwerft',
            125 => 'LKW Fabrik',
        ],
        'en' => [
            6   => 'Concrete factory',
            23  => 'Fertilizer factory',
            25  => 'Brick factory',
            29  => 'Insecticides factory',
            31  => 'Ironworks',
            33  => 'Aluminium factory',
            34  => 'Silver refinery',
            37  => 'Copper refinery',
            39  => 'Oil refinery',
            52  => 'Titanium refinery',
            61  => 'Glacier\'s workshop',
            63  => 'Plastics factory',
            68  => 'Silicon refinery',
            69  => 'Electronics factory',
            76  => 'Medical technology Inc.',
            80  => 'Gold refinery',
            85  => 'Goldsmith',
            91  => 'Lithium refinery',
            95  => 'Battery factory',
            101 => 'Arms factory',
            118 => 'Drone shipyard',
            125 => 'Truck plant',
        ],
    ],
];
